name: Reposync
description: Syncs files onto project repository

outputs:
  types:
    description: "Detected project types"
    value: ${{ steps.detect.outputs.types }}
  features:
    description: "Detected project features"
    value: ${{ steps.detect.outputs.features }}

runs:
  using: "composite"
  steps:
    - name: Checkout central repository
      uses: actions/checkout@v4
      with:
        repository: fredrikaverpil/github
        path: central

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Build reposync CLI
      shell: bash
      run: |
        cd central
        go build -o ./bin/reposync ./cmd/reposync

    - name: Test binary
      id: bintest
      shell: bash
      run: |
        central/bin/reposync -h

  # TODO: implement
  # - name: Detect project types
  #   id: detect
  #   shell: bash
  #   run: |
  #     central/bin/reposync -dir . detect -output $GITHUB_OUTPUT
  # - name: Generate dependabot config
  #   shell: bash
  #   run: |
  #     central/bin/reposync -dir . dependabot
  # - name: Sync workflows
  #   shell: bash
  #   run: |
  #     central/bin/reposync -dir . sync -source central/templates
