name: sync-workflows

on:
  workflow_dispatch:
    inputs:
      pr-title:
        description: 'PR title'
        required: false
        default: 'chore: update workflows from central repo'

jobs:
  sync:
    name: Sync Workflows
    uses: fredrikaverpil/github/.github/workflows/sync-runner.yml@main
    with:
      pr-title: ${{ inputs.pr-title }}
    secrets:
      WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
