name: Sync reusable workflows

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1" # Monday at 8am

jobs:
  sync:
    name: workflows
    uses: fredrikaverpil/github/.github/workflows/sync-runner.yml@main
    secrets:
      WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
