name: sync-workflows

on:
  workflow_dispatch:
    inputs:
      branch-name:
        description: 'Branch name for the PR'
        required: false
        default: 'chore/update-workflows'
      pr-title:
        description: 'PR title'
        required: false
        default: 'chore: update workflows from central repo'

jobs:
  sync:
    name: Sync Workflows
    uses: fredrikaverpil/github/.github/workflows/sync-runner.yml@main
    with:
      branch-name: ${{ inputs.branch-name }}
      pr-title: ${{ inputs.pr-title }}
