name: sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1" # Monday at 8am

jobs:
  sync:
    name: sync workflows with https://github.com/fredrikaverpil/github
    uses: fredrikaverpil/github/.github/workflows/sync-runner.yml@main
    secrets:
      WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
