name: python

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 8 * * 1" # Monday at 8am

jobs:
  ci:
    uses: fredrikaverpil/github/.github/workflows/python.yml@main
