name: sync-workflows

description: syncs workflows onto project repository

outputs:
  types:
    description: detected project types
    value: ${{ steps.detect.outputs.types }}

runs:
  using: "composite"
  steps:
    - name: checkout fredrikaverpil/github
      uses: actions/checkout@v4
      with:
        repository: fredrikaverpil/github
        path: central

    - name: make sync.sh executable
      shell: bash
      run: chmod +x central/.github/actions/sync-workflows/sync.sh

    - name: perform sync
      id: detect
      shell: bash
      run: |
        central/.github/actions/sync-workflows/sync.sh . central/templates $GITHUB_OUTPUT

    - name: display detected types
      shell: bash
      run: |
        echo "detected types: ${{ steps.detect.outputs.types }}"

    - name: cleanup
      shell: bash
      run: rm -rf central
