name: sync-workflows

description: syncs workflows onto project repository

runs:
  using: "composite"
  steps:
    - name: Set environment variable
      shell: bash
      run: |
        echo "TMP_REPO_PATH=.tmp_repo" >> $GITHUB_ENV

    - name: checkout fredrikaverpil/github
      uses: actions/checkout@v4
      with:
        repository: fredrikaverpil/github
        path: ${{ env.TMP_REPO_PATH }}
        ref: main

    - name: perform sync
      shell: bash
      run: |
        python ${{ env.TMP_REPO_PATH }}/.github/actions/sync-workflows/sync.py . central/templates

    - name: cleanup
      shell: bash
      run: rm -rf ${{ env.TMP_REPO_PATH }}
