name: goreleaser

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  ci:
    uses: fredrikaverpil/github/.github/workflows/goreleaser.yml@main
    with:
      go-version-file: go.mod
    secrets: inherit
