name: goreleaser

on:
  workflow_dispatch:
  tags:
    - "v*.*.*"

permissions:
  contents: write

jobs:
  ci:
    uses: fredrikaverpil/github/.github/workflows/goreleaser.yml@main
    with:
      go-version-file: go.mod
    secrets:
      # pass on the GITHUB_TOKEN
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
