name: gen-dependabot

on:
  workflow_call:
    inputs:
      file_patterns:
        description: 'File patterns to include for dependabot detection (comma-separated)'
        required: false
        type: string
        default: 'go.mod,pyproject.toml,uv.lock,requirements.txt,package.json'
      exclude_patterns:
        description: 'File patterns to exclude from dependabot detection (comma-separated)'
        required: false
        type: string
        default: ''
    secrets:
      SYNC_TOKEN:
        required: true

jobs:
  find-dirs:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.find-dirs.outputs.matrix }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: find project directories
        id: find-dirs
        uses: fredrikaverpil/github/.github/actions/find-dirs@main
        with:
          file_patterns: ${{ inputs.file_patterns }}
          exclude_patterns: ${{ inputs.exclude_patterns }}

  sync:
    runs-on: ubuntu-latest
    needs: find-dirs
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: generate dependabot.yml
        uses: fredrikaverpil/github/.github/actions/generate-dependabot@main
        with:
          matrix: ${{ needs.find-dirs.outputs.matrix }}

      - name: run sync-workflows action
        uses: fredrikaverpil/github/.github/actions/sync-workflows@main

      - name: create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.SYNC_TOKEN }}
          commit-message: "ci(workflows): sync with fredrikaverpil/github"
          title: "ci(workflows): sync with fredrikaverpil/github"
          body: |
            This PR syncs the GitHub repo with CI workflows from the [fredrikaverpil/github](https://github.com/fredrikaverpil/github) repository.
          branch: ci/sync-workflows
          delete-branch: true
