name: gen-dependabot

on:
  workflow_call:

jobs:
  find-dirs:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.find-dirs.outputs.matrix }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: find project directories
        id: find-dirs
        uses: fredrikaverpil/github/.github/actions/find-dirs@main
        with:
          file_patterns: "go.mod,pyproject.toml,uv.lock,requirements.txt,package.json"

  sync:
    runs-on: ubuntu-latest
    needs: find-dirs
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: generate dependabot.yml
        uses: fredrikaverpil/github/.github/actions/generate-dependabot@main
        with:
          matrix: ${{ needs.find-dirs.outputs.matrix }}

      - name: run sync-workflows action
        uses: fredrikaverpil/github/.github/actions/sync-workflows@main

      - name: create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.SYNC_TOKEN }}
          commit-message: "ci(dependabot): sync with fredrikaverpil/github"
          title: "ci(dependabot): sync with fredrikaverpil/github"
          body: |
            This PR syncs the GitHub repo with a generated `dependabot.yml` file from the [fredrikaverpil/github](https://github.com/fredrikaverpil/github) repository.
          branch: ci/sync-dependabot
          delete-branch: true
