name: lint

on:
  workflow_call:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [stable] # rc versions are defined like 1.24.0-rc.3
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64
          args: --config https://gist.githubusercontent.com/maratori/47a4d00457a92aa426dbd48a18776322/raw/dba9604b2f7fc0dff12c1ed793256ca2bc0111ab/.golangci.yml
