name: lint

on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: 'stable' # rc versions are defined like 1.24.0-rc.3
      working-directory:
        description: 'Directory to run golangci-lint in'
        required: false
        type: string
        default: '.'
      config-source:
        description: 'Source for golangci-lint config (local, golden-latest, golden-revision, central)'
        required: false
        type: string
        default: 'golden-latest'
      gist-revision:
        description: 'Specific Gist revision SHA (used only with golden-revision source)'
        required: false
        type: string
        default: ''

jobs:
  find-dirs:
    uses: ./.github/workflows/find-dirs.yml
    with:
      file_patterns: go.mod

  golangci:
    name: lint-${{ matrix.dir }}
    needs: find-dirs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.find-dirs.outputs.matrix) }}
    env:
      GOTOOLCHAIN: local
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ${{ matrix.dir }}/go.mod
      - name: golangci-lint
        uses: fredrikaverpil/github/.github/actions/golangci-lint@main
        with:
          working-directory: ${{ matrix.dir }}
          config-source: ${{ inputs.config-source }}
          gist-revision: ${{ inputs.gist-revision }}
