name: lint

on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: 'stable' # rc versions are defined like 1.24.0-rc.3

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}
      - name: golangci-lint
        uses: ./.github/actions/golangci-lint

