
name: test

on:
  workflow_call:

jobs:
  find-dirs:
    uses: fredrikaverpil/github/.github/workflows/find-dirs.yml@main
    with:
      file_patterns: go.mod

  go:
    runs-on: ubuntu-latest
    needs: find-dirs
    strategy:
      fail-fast: false
      matrix:
        dir: ${{ fromJson(needs.find-dirs.outputs.matrix).dir }}
    env:
      GOTOOLCHAIN: local
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ${{ matrix.dir }}/go.mod
      - run: go test ./...

