name: vuln

on:
  workflow_call:

jobs:
  find-dirs:
    uses: fredrikaverpil/github/.github/workflows/find-dirs.yml@main
    with:
      file_patterns: go.mod

  govulncheck:
    runs-on: ubuntu-latest
    needs: find-dirs
    strategy:
      fail-fast: false
      matrix:
        dir: ${{ fromJson(needs.find-dirs.outputs.matrix).dir }}
    env:
      GOTOOLCHAIN: local
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ${{ matrix.dir }}/go.mod
      - run: go version
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          work-dir: ${{ matrix.dir }}
          go-version-file: ${{ matrix.dir }}/go.mod

  gosec:
    runs-on: ubuntu-latest
    needs: find-dirs
    strategy:
      fail-fast: false
      matrix:
        dir: ${{ fromJson(needs.find-dirs.outputs.matrix).dir }}
    env:
      GOTOOLCHAIN: local
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ${{ matrix.dir }}/go.mod
      - run: go version
      - run: go install github.com/securego/gosec/v2/cmd/gosec@latest
      - run: gosec ./...
        working-directory: ${{ matrix.dir }}

