name: goreleaser

on:
  workflow_call:
    inputs:
      go-version-file:
        required: true
        type: string
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for goreleaser to get tag information

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ inputs.go-version-file }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6  # Use the latest version
        with:
          distribution: goreleaser
          version: latest
          args: release --clean  # '--clean' removes the dist folder before building
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
