name: pr

on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  title:
    name: validate
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          requireScope: false
          subjectPattern: ^(?![A-Z]).+$
          scopes: |
            .+
          types: |
            build
            chore
            ci
            docs
            feat
            fix
            merge
            perf
            refactor
            revert
            style
            test
            wip
          ignoreLabels: |
            autorelease: pending
