name: release

on:
  workflow_call:
    secrets:
      SYNC_TOKEN:
        required: true

jobs:
  please:
    if: ${{ !failure() && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: release-please config
        id: release-please-config
        run: |
          if [ -f .github/release-please-config.json ]; then
            echo "config-file=.github/release-please-config.json" >> $GITHUB_OUTPUT
            [ -f .github/release-please-manifest.json ] &&
              echo "manifest-file=.github/release-please-manifest.json" >> $GITHUB_OUTPUT
            [ -f .github/.release-please-manifest.json ] &&
              echo "manifest-file=.github/.release-please-manifest.json" >> $GITHUB_OUTPUT
          else
            echo "release-type=simple" >> $GITHUB_OUTPUT
          fi
          exit 0
      - uses: googleapis/release-please-action@v4
        # https://github.com/googleapis/release-please-action
        # https://github.com/googleapis/release-please/blob/main/docs/customizing.md
        id: release
        with:
          token: ${{ secrets.SYNC_TOKEN }}
          config-file: ${{ steps.release-please-config.outputs.config-file }}
          release-type: ${{ steps.release-please-config.outputs.release-type }}
          # https://github.com/googleapis/release-please-action#package-options
          manifest-file: ${{ steps.release-please-config.outputs.manifest-file }}
