name: stale

on:
  workflow_call:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v10
        with:
          stale-issue-message: "This issue has been open for **30 days** with no activity. Remove the stale label or add a comment or it will be closed in another **30 days**."
          stale-pr-message: "This PR has been open for **30 days** with no activity. Remove the stale label or add a comment or it will be closed in another **30 days**."
          close-issue-message: "This issue was closed because it has been stalled for a long time with no activity."
          close-pr-message: "This PR was closed because it has been stalled for a long time with no activity."
          days-before-stale: 30
          days-before-close: 30
          exempt-pr-labels: dependencies,pinned,bug
          exempt-issue-labels: dependencies,pinned,bug
