name: sync-workflows-runner

on:
  workflow_call:
    inputs:
      branch-name:
        required: false
        type: string
        default: 'chore/update-workflows'
      pr-title:
        required: false
        type: string
        default: 'chore: update workflows from central repo'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git checkout -b ${{ inputs.branch-name }}

      - name: Detect project types
        id: detect
        run: |
          # Go detection
          if [ -f "go.mod" ]; then
            GO_DETECTED="true"
          else
            GO_DETECTED="false"
          fi

          # Python detection
          if [ -f "pyproject.toml" ] || [ -f "setup.py" ] || [ -f "requirements.txt" ]; then
            PYTHON_DETECTED="true"
          else
            PYTHON_DETECTED="false"
          fi

          # Lua detection
          if ls *.lua 1> /dev/null 2>&1 || [ -f ".luacheckrc" ]; then
            LUA_DETECTED="true"
          else
            LUA_DETECTED="false"
          fi

          # Output detection results
          echo "go_detected=$GO_DETECTED" >> $GITHUB_OUTPUT
          echo "python_detected=$PYTHON_DETECTED" >> $GITHUB_OUTPUT
          echo "lua_detected=$LUA_DETECTED" >> $GITHUB_OUTPUT

      - name: Download Go workflows
        if: steps.detect.outputs.go_detected == 'true'
        run: |
          mkdir -p .github/workflows
          curl -s https://raw.githubusercontent.com/fredrikaverpil/github/main/templates/go/workflow.yml -o .github/workflows/go.yml
          curl -s https://raw.githubusercontent.com/fredrikaverpil/github/main/.github/workflows/go-lint.yml -o .github/workflows/go-lint.yml
          curl -s https://raw.githubusercontent.com/fredrikaverpil/github/main/.github/workflows/go-vuln.yml -o .github/workflows/go-vuln.yml

          # Copy golangci-lint action
          mkdir -p .github/actions/golangci-lint
          curl -s https://raw.githubusercontent.com/fredrikaverpil/github/main/.github/actions/golangci-lint/action.yml -o .github/actions/golangci-lint/action.yml
          curl -s https://raw.githubusercontent.com/fredrikaverpil/github/main/.github/actions/golangci-lint/.golangci.yml -o .github/actions/golangci-lint/.golangci.yml

      - name: Download Python workflows
        if: steps.detect.outputs.python_detected == 'true'
        run: |
          mkdir -p .github/workflows
          curl -s https://raw.githubusercontent.com/fredrikaverpil/github/main/templates/python/workflow.yml -o .github/workflows/python.yml

      - name: Download Lua workflows
        if: steps.detect.outputs.lua_detected == 'true'
        run: |
          mkdir -p .github/workflows
          curl -s https://raw.githubusercontent.com/fredrikaverpil/github/main/templates/lua/workflow.yml -o .github/workflows/lua.yml

      - name: Download common workflows
        run: |
          mkdir -p .github/workflows
          curl -s https://raw.githubusercontent.com/fredrikaverpil/github/main/templates/common/pr.yml -o .github/workflows/pr.yml
          # Download sync workflow to keep it updated as well
          curl -s https://raw.githubusercontent.com/fredrikaverpil/github/main/templates/sync/sync.yml -o .github/workflows/sync.yml

          # Download dependabot config
          mkdir -p .github
          curl -s https://raw.githubusercontent.com/fredrikaverpil/github/main/templates/common/dependabot.yml -o .github/dependabot.yml

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          git add .
          git commit -m "${{ inputs.pr-title }}"
          git push origin ${{ inputs.branch-name }}

      - name: Create Pull Request
        if: steps.changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ inputs.branch-name }}
          title: ${{ inputs.pr-title }}
          body: |
            This PR updates the GitHub workflows from the central repository.

            Project types detected:
            - Go: ${{ steps.detect.outputs.go_detected }}
            - Python: ${{ steps.detect.outputs.python_detected }}
            - Lua: ${{ steps.detect.outputs.lua_detected }}

            Automated by the sync-workflows action.
          labels: ci
          delete-branch: true
