name: test find-dirs

on:
  push:
    branches:
      - main
    paths:
      - 'composite-actions/find-dirs/**'
  pull_request:
    paths:
      - 'composite-actions/find-dirs/**'
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - run: |
          cd composite-actions/find-dirs
          python -m unittest test_find_dirs.py
