name: tools-cache

on:
  workflow_call:
    inputs:
      go-versions:
        required: false
        type: string
        default: '["stable"]'
      os-versions:
        required: false
        type: string
        default: '["ubuntu-latest"]'
    outputs:
      week:
        description: "Week number for cache key"
        value: ${{ jobs.get-date.outputs.week }}

jobs:
  get-date:
    runs-on: ubuntu-latest
    outputs:
      week: ${{ steps.date.outputs.week }}
    steps:
      - id: date
        run: echo "week=$(date +'%Y-%U')" >> $GITHUB_OUTPUT

  tools-cache:
    needs: [get-date]
    strategy:
      fail-fast: false
      matrix:
        go-version: ${{ fromJson(inputs.go-versions) }}
        os-version: ${{ fromJson(inputs.os-versions) }}
    runs-on: ${{ matrix.os-version }}
    env:
      GOTOOLCHAIN: local
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: false
      - name: cache go tools
        uses: actions/cache@v4
        id: tools-cache
        with:
          path: |
            ~/go/bin
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-tool-${{ runner.os }}-go${{ matrix.go-version }}-${{ needs.get-date.outputs.week }}
          restore-keys: |
            go-tool-${{ runner.os }}-go${{ matrix.go-version }}-
            go-tool-${{ runner.os }}-
      - name: Install Go tools
        run: go install tool
        working-directory: ${{ github.workspace }}/tools
      - name: Install Task
        run: go install github.com/go-task/task/v3/cmd/task@latest
      - name: review ~/go/bin
        run: ls -alh ~/go/bin
