name: go

on:
  workflow_call:
    inputs:
      # go-version:
      #   required: false
      #   type: string
      #   default: 'stable' # rc versions are defined like 1.24.0-rc.3
      working-directory:
        description: 'Directory to run golangci-lint in'
        required: false
        type: string
        default: '.'
      config-source:
        description: 'Source for golangci-lint config (local, golden-latest, golden-revision, central)'
        required: false
        type: string
        default: 'golden-latest'
      gist-revision:
        description: 'Specific Gist revision SHA (used only with golden-revision source)'
        required: false
        type: string
        default: ''

jobs:
  find-dirs:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.find-dirs.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: find-dirs
        uses: fredrikaverpil/github/composite-actions/find-dirs@main
        with:
          file_patterns: go.mod
          exclude_patterns: /tools

  setup-tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: cache go tools
        uses: actions/cache@v4
        id: tools-cache
        with:
          path: ~/go/bin
          key: go-tools-${{ runner.os }}-${{ hashFiles('tools/go.mod') }}
      - name: Install Go tools
        if: steps.tools-cache.outputs.cache-hit != 'true'
        run: |
          go install -modfile=tools/go.mod tool

  format:
    runs-on: ubuntu-latest
    needs: [find-dirs, setup-tools]
    strategy:
      fail-fast: false
      matrix:
        dir: ${{ fromJson(needs.find-dirs.outputs.matrix).dir }}
    env:
      GOTOOLCHAIN: local
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ${{ matrix.dir }}/go.mod
      - uses: actions/cache@v4
        with:
          path: ~/go/bin
          key: go-tools-${{ runner.os }}-${{ hashFiles('tools/go.mod') }}
      - run: goimports -w .
      - run: gci write --skip-generated --skip-vendor -s standard -s default .
      - run: gofumpt
      # FIXME: FATAL Error formatting source: exec: "gofumpt": executable file not found in $PATH
      # - run: golines --base-formatter=gofumpt --ignore-generated --tab-len=1 --max-len=120 --write-output .
      - run: golines --ignore-generated --tab-len=1 --max-len=120 --write-output .
      - run: git diff --exit-code

  golangci-lint:
    needs: [find-dirs, setup-tools]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dir: ${{ fromJson(needs.find-dirs.outputs.matrix).dir }}
    env:
      GOTOOLCHAIN: local
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ${{ matrix.dir }}/go.mod
      - uses: actions/cache@v4
        with:
          path: ~/go/bin
          key: go-tools-${{ runner.os }}-${{ hashFiles('tools/go.mod') }}
      - uses: fredrikaverpil/github/composite-actions/golangci-lint@main
        with:
          working-directory: ${{ matrix.dir }}
          config-source: ${{ inputs.config-source }}
          gist-revision: ${{ inputs.gist-revision }}

  govulncheck:
    runs-on: ubuntu-latest
    needs: find-dirs
    strategy:
      fail-fast: false
      matrix:
        dir: ${{ fromJson(needs.find-dirs.outputs.matrix).dir }}
    env:
      GOTOOLCHAIN: local
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ${{ matrix.dir }}/go.mod
      # NOTE: does not use govulncheck from the go.mod
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          work-dir: ${{ matrix.dir }}
          go-version-file: ${{ matrix.dir }}/go.mod

  gopls:
    runs-on: ubuntu-latest
    needs: find-dirs
    strategy:
      fail-fast: false
      matrix:
        dir: ${{ fromJson(needs.find-dirs.outputs.matrix).dir }}
    env:
      GOTOOLCHAIN: local
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ${{ matrix.dir }}/go.mod
      # NOTE: does not play well with `go tool`, causes golang.org/x/tools conflicts
      - run: go install golang.org/x/tools/gopls@latest
      - run: gopls stats
        working-directory: ${{ matrix.dir }}

  gosec:
    runs-on: ubuntu-latest
    needs: [find-dirs, setup-tools]
    strategy:
      fail-fast: false
      matrix:
        dir: ${{ fromJson(needs.find-dirs.outputs.matrix).dir }}
    env:
      GOTOOLCHAIN: local
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ${{ matrix.dir }}/go.mod
      - uses: actions/cache@v4
        with:
          path: ~/go/bin
          key: go-tools-${{ runner.os }}-${{ hashFiles('tools/go.mod') }}
      - run: gosec ./...
        working-directory: ${{ matrix.dir }}

  test:
    runs-on: ubuntu-latest
    needs: find-dirs
    strategy:
      fail-fast: false
      matrix:
        dir: ${{ fromJson(needs.find-dirs.outputs.matrix).dir }}
    env:
      GOTOOLCHAIN: local
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ${{ matrix.dir }}/go.mod
      - run: go test ./...

  vet:
    runs-on: ubuntu-latest
    needs: find-dirs
    strategy:
      fail-fast: false
      matrix:
        dir: ${{ fromJson(needs.find-dirs.outputs.matrix).dir }}
    env:
      GOTOOLCHAIN: local
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ${{ matrix.dir }}/go.mod
      - run: go vet ./...

